name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.authors}
main: ${project.main}
depend: [ProtocolLib]
commands:
  auracheck:
    description: Main AuraCheck command
    usage: /<command> <subcommand>
    aliases: [ac]
    permission: auracheck.check
